tpa-prereqs:
  namespace: trusted-profile-analyzer
  objectBucketClaim:
    name: tpa-bucket-claim
    bucketName: tpa-bucket
    storageClassName: openshift-storage.noobaa.io
  keycloak:
    namespace: keycloak
    host: ""
    realm: sso
  oidc:
    clientId: tpa-cli
    clientSecret: ""
    frontendClientId: tpa-frontend
  tpaRouteHost: ""
  adminEmail: admin@demo.redhat.com

tpa-postgresql:
  namespace: trusted-profile-analyzer
  image: registry.redhat.io/rhel10/postgresql-18
  credentials:
    dbHost: "tpa-postgresql"
    dbName: "tpadb"
    dbUser: "tpauser"
    dbPassword: "r3dh8t1!"
    dbAdmin: "postgres"
    dbAdminPassword: "adminr3dh8t1!"
    dbPort: "5432"
  storage:
    size: 30Gi

tpa-server:
  namespace: trusted-profile-analyzer
  chartVersion: "*"
  subdomain: ""
  keycloak:
    host: ""
    realm: sso
  oidc:
    frontendClientId: tpa-frontend
    cliClientId: tpa-cli
  objectBucketClaim:
    name: tpa-bucket-claim
    bucketName: tpa-bucket
  argocd:
    namespace: openshift-gitops

tpa-dataset:
  namespace: trusted-profile-analyzer
  datasetUrl: "https://raw.githubusercontent.com/redhat-tssc-tmm/rhdp-tpa-demo/main/datasets/tpa-demo-dataset-v2.zip"
  image: registry.redhat.io/ubi9/ubi
  keycloak:
    host: ""
    realm: sso
  oidc:
    clientId: tpa-cli

tpa-db-monitor:
  namespace: trusted-profile-analyzer
  image: quay.io/tssc_demos/tpa-db-monitor:latest
  routeHost: ""

tpa-rhda-backend:
  namespace: rhda-backend
  image: quay.io/tssc_demos/trustify-dependency-analytics:v3.1.0
  initImage: registry.redhat.io/ubi9/openjdk-21-runtime:1.23
  tpaNamespace: trusted-profile-analyzer
  subdomain: ""
  oidc:
    clientId: tpa-cli
    clientSecret: ""
    keycloakHost: ""
    realm: sso
  postgresql:
    image: registry.redhat.io/rhel10/postgresql-18
    storage: 1Gi
    database: trustify_da
    username: trustify_da
    password: "r3dh8t1!"
  redis:
    image: registry.redhat.io/rhel9/redis-7:latest
    storage: 1Gi
  routeHost: ""
