apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator
  namespace: {{ include "rhacs-operator.namespace" . }}
  annotations:
    {{- include "rhacs-operator.argocd-syncwave" . | nindent 4 }}
spec:
  upgradeStrategy: Default
