apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhacs-sso-secret
  namespace: {{ include "rhacs-sso-config.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave.externalSecret | quote }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: rhacs-sso-secret
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: secrets/rhacs/client-secret
        property: clientId
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: secrets/rhacs/client-secret
        property: clientSecret
