apiVersion: v1
kind: Secret
metadata:
  name: rhacs-declarative-auth
  namespace: {{ include "rhacs-sso-config.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave.externalSecret | quote }}
type: Opaque
stringData:
  auth-provider.yaml: |
    name: Keycloak SSO
    minimumRole: None
    uiEndpoint: central-{{ include "rhacs-sso-config.namespace" . }}.{{ .Values.cluster.subdomain }}
    groups:
      - key: email
        value: {{ .Values.rhacs.adminEmail }}
        role: Admin
    oidc:
      issuer: https://{{ .Values.keycloak.host }}/realms/{{ .Values.keycloak.realm }}
      mode: post
      clientID: {{ .Values.rhacs.clientId }}
      clientSecret: {{ .Values.rhacs.clientSecret }}
