apiVersion: v1
kind: Secret
metadata:
  name: oidc-cli
  namespace: {{ include "tpa-prereqs.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave.prereqs | quote }}
type: Opaque
stringData:
  client-secret: {{ .Values.oidc.clientSecret | quote }}
