apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: policy-controller-operator
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  upgradeStrategy: Default
