{{- $prefix := include "tpa-tenant.prefix" . -}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.tpa.objectBucketClaim.name }}
  namespace: {{ $prefix }}-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  bucketName: {{ $prefix }}-{{ .Values.tpa.objectBucketClaim.bucketName }}
  storageClassName: {{ .Values.tpa.objectBucketClaim.storageClassName }}
