{{- $prefix := include "tpa-tenant.prefix" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-cli
  namespace: {{ $prefix }}-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  client-secret: {{ .Values.tpa.oidc.clientSecret | quote }}
