{{- $prefix := include "tpa-tenant.prefix" . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-cli
  namespace: {{ $prefix }}-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: oidc-cli
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: secrets/tpa/client-secret
        property: clientSecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-cli
  namespace: {{ $prefix }}-rhda
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: oidc-cli
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: secrets/tpa/client-secret
        property: clientSecret
