namespace: trusted-artifact-signer

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: rhtas-operator
  source: redhat-operators-snapshot
  sourceNamespace: openshift-marketplace
