---
apiVersion: v1
kind: Secret
metadata:
  name: rhda-backend-secret
  labels:
    app: rhda-backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  rhtpa.client.id: {{ .Values.oidc.clientId | quote }}
  rhtpa.client.secret: {{ .Values.oidc.clientSecret | quote }}
  rhtpa.auth.server.url: "https://{{ .Values.oidc.keycloakHost }}/realms/{{ .Values.oidc.realm }}"
