---
apiVersion: v1
kind: Secret
metadata:
  name: rhda-backend-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: rhda-backend-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  database-name: {{ .Values.postgresql.database | quote }}
  database-user: {{ .Values.postgresql.username | quote }}
  database-password: {{ .Values.postgresql.password | quote }}
