---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhda-backend-redis
  labels:
    app: rhda-backend-redis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
