---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpa-postgresql-data
  labels:
    app: tpa-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
