apiVersion: v1
kind: ConfigMap
metadata:
  name: rhacs-tenant-config
  namespace: {{ include "rhacs-central.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave.namespace | quote }}
